name: Run Streamlit App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env

      - name: Build and run Docker container
        run: docker run -p 8504:8501 -v $(pwd)/.env:/app/.env streamlit-app
